### PR TITLE
PLANNER-1353 switch from jboss-parent to kie-parent

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.jboss.org/browse/PLANNER-1353 and https://issues.jboss.org/browse/PLANNER-1342

Switched parent to kie-parent and fixed all issues with that related change:
- enforcer violations
- GWT compilation

### CODE REVIEW

File: employee-rostering-gwtui/pom.xml [hunk 1]
```diff
@@ -72,6 +118,40 @@
...
+      <groupId>com.google.elemental2</groupId>
+      <artifactId>elemental2-core</artifactId>
+    </dependency>
+    <dependency>
+      <groupId>com.google.elemental2</groupId>
+      <artifactId>elemental2-dom</artifactId>
+    </dependency>
+    <dependency>
+      <groupId>com.google.elemental2</groupId>
+	  <artifactId>elemental2-promise</artifactId>
```
Comment (rsynek) [inline employee-rostering-gwtui/pom.xml]: Indentation

File: employee-rostering-gwtui/pom.xml [hunk 2]
```diff
@@ -72,6 +118,40 @@
...
     </dependency>
+    <dependency>
+      <groupId>org.jboss.errai</groupId>
+      <artifactId>errai-bus</artifactId>
+    </dependency>
+    <dependency>
+      <groupId>org.jboss.errai</groupId>
+      <artifactId>errai-common</artifactId>
+    </dependency>    
+    <!-- kie-parent excludes this from errai-ioc, but it is required for GWT compile  -->
```
Comment (rsynek) [inline employee-rostering-gwtui/pom.xml]: Does this comment apply only to `com.google.inject:guice` or to other dependencies below as well? There were many new dependencies added - these are not transitive?

File: pom.xml [hunk 3]
```diff
@@ -73,13 +72,15 @@
...
     <version.org.optaplanner>${project.version}</version.org.optaplanner>
+    <version.org.kie.soup>${project.version}</version.org.kie.soup>
     <version.org.slf4j>1.7.25</version.org.slf4j>
     <version.org.webjars.bower.org.patternfly>3.18.1</version.org.webjars.bower.org.patternfly>
     <version.org.webjars.Eonasdan-bootstrap-datetimepicker>4.17.47</version.org.webjars.Eonasdan-bootstrap-datetimepicker>
     <version.org.webjars.momentjs>2.22.2</version.org.webjars.momentjs>
     <version.org.wildfly-plugins.wildfly-maven-plugin>1.2.0.Final</version.org.wildfly-plugins.wildfly-maven-plugin>
     <version.org.wildfly>14.0.1.Final</version.org.wildfly>
     <version.org.codehaus.cargo.cargo-maven2-plugin>1.6.11</version.org.codehaus.cargo.cargo-maven2-plugin>
+    <version.org.mockito>2.12.0</version.org.mockito>
```
Comment (Christopher-Chianelli) [inline pom.xml]: You introduced this property but I don't see it used anywhere? Also, doesn't kie-parent define the version of Mockito?

File: employee-rostering-gwtui/pom.xml (hunk 2 above)
Comment (mareknovotny) [reply employee-rostering-gwtui/pom.xml]: it is related to the guice

File: pom.xml (hunk 3 above)
Comment (mareknovotny) [reply pom.xml]: it is overriding the kie-parent version property. Here you used 2.12.0, but kie-parent uses 1.x and you used not backward compatible API/method, so therefore there is required that overriding

Comment (mareknovotny) [reply pom.xml]: or the version property is defined in IP BOM ;)

**Comment by mareknovotny** [comment]
I reformatted the pom.xml files

File: pom.xml (hunk 3 above)
Comment (Christopher-Chianelli) [reply pom.xml]: Does simply changing the version String actually do that? I would think you need to put something in dependency management in order to actually do that. If that the case, can you please add a comment above the property explaining that we are overriding kie-parent version of mockito since we are using gwtmockito (which, if I remember correctly, is the dependency that set the mockito version)?

File: employee-rostering-gwtui/pom.xml (hunk 2 above)
Comment (rsynek) [reply employee-rostering-gwtui/pom.xml]: @mareknovotny Ok, so why so many new dependencies? Are they being used directly in this project and were not declared as such?

File: employee-rostering-gwtui/pom.xml [hunk 4]
```diff
@@ -1,6 +1,6 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
-         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
+  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
```
Comment (yurloc) [inline employee-rostering-gwtui/pom.xml]: Please keep the XML attributes aligned. I'm not sure if it's defined in KIE Java Conventions but at least to keep consistency inside this project.

Comment (mareknovotny) [reply employee-rostering-gwtui/pom.xml]: The latest update fixed the namespace indentation

File: pom.xml [hunk 5]
```diff
@@ -256,6 +263,12 @@
         <artifactId>swagger-annotations</artifactId>
         <version>${version.io.swagger}</version>
       </dependency>
+      <dependency>
+      	<groupId>net.bytebuddy</groupId>
+      	<artifactId>byte-buddy</artifactId>
```
[the remark this answers is not in the document]
Comment (mareknovotny) [reply pom.xml]: not sure what do you mean by "when it can be removed". Anything transitive used in project needs to be declared that enforcer plugin notifies.

[the remark this answers is not in the document]
Comment (yurloc) [reply pom.xml]: Kie-parent overrides version of one of Mockito's runtime dependencies and that causes troubles. It's a bit complicated and I'm not sure what's the best solution. This is a workaround and might break whenever we upgrade Mockito. Let's talk in person.

File: employee-rostering-server/pom.xml [hunk 6]
```diff
@@ -41,6 +41,26 @@
...
+	  <groupId>com.fasterxml.jackson.datatype</groupId>
+	  <artifactId>jackson-datatype-jsr310</artifactId>
+	</dependency>
+	<dependency>
+	  <groupId>org.apache.commons</groupId>
+	  <artifactId>commons-lang3</artifactId>
+	</dependency>
+	<dependency>
+	  <groupId>org.optaplanner</groupId>
+	  <artifactId>optaplanner-persistence-common</artifactId>
```
[the remark this answers is not in the document]
Comment (mareknovotny) [reply employee-rostering-server/pom.xml]: I saw that the enforcer shows some other issues on CI, which I haven't seen locally. I will need to find out why.

[the remark this answers is not in the document]
Comment (mareknovotny) [reply employee-rostering-server/pom.xml]: Where do you see that not used warning/error?

[the remark this answers is not in the document]
Comment (yurloc) [reply employee-rostering-server/pom.xml]:
```
$ mvn dependency:analyze
...
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ employee-rostering-server ---
[WARNING] Unused declared dependencies found:
[WARNING]    org.optaplanner:optaplanner-persistence-common:jar:7.15.0-SNAPSHOT:compile
[WARNING]    ch.qos.logback:logback-classic:jar:1.2.3:test
```

(Don't worry about logbac-classic, the dependency plugin can't detect runtime dependencies.)

**Comment by mareknovotny** [comment]
@yurloc @Christopher-Chianelli @rsynek please review after the last changes too ;)

File: pom.xml [hunk 7]
```diff
@@ -73,13 +72,18 @@
     <version.org.gwtbootstrap3>0.9.4</version.org.gwtbootstrap3>
     <version.org.jboss.errai>4.3.3.Final</version.org.jboss.errai>
     <version.org.optaplanner>${project.version}</version.org.optaplanner>
+    <version.org.kie.soup>${project.version}</version.org.kie.soup>
     <version.org.slf4j>1.7.25</version.org.slf4j>
     <version.org.webjars.bower.org.patternfly>3.18.1</version.org.webjars.bower.org.patternfly>
     <version.org.webjars.Eonasdan-bootstrap-datetimepicker>4.17.47</version.org.webjars.Eonasdan-bootstrap-datetimepicker>
     <version.org.webjars.momentjs>2.22.2</version.org.webjars.momentjs>
     <version.org.wildfly-plugins.wildfly-maven-plugin>1.2.0.Final</version.org.wildfly-plugins.wildfly-maven-plugin>
```
Comment (Christopher-Chianelli) [inline pom.xml]: Do we still need this? I notice you removed the version from the wildfly-maven-plugin plugin but didn't remove the property. If it the same case as mockito, add a comment above it. Otherwise, remove the property.

Comment (mareknovotny) [reply pom.xml]: no, good catch, I removed that version property now.

File: employee-rostering-server/pom.xml (hunk 6 above)
[the remark this answers is not in the document]
Comment (mareknovotny) [reply employee-rostering-server/pom.xml]: ok, removed that GAV

**Comment by mareknovotny** [comment]
added a comment for net.bytebuddy version property after discussion with @yurloc

**Comment by yurloc** [comment]
Jenkin retest this. The build was broken by https://github.com/kiegroup/appformer/pull/526.

**Comment by yurloc** [comment]
Jenkins retest this. Build broken by https://github.com/kiegroup/appformer/pull/526.

**Comment by yurloc** [comment]
Doesn't work on my machine :laughing: 

During mvn clean install in employee-rostering-gwtui:
```
[INFO] --- gwt-maven-plugin:1.0-rc-9:compile (default-compile) @ employee-rostering-gwtui ---
[INFO] Compiling module org.optaweb.employeerostering.gwtui.WorkerRosteringWebapp
[INFO]    Ignored 2 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]    Computing all possible rebind results for 'org.jboss.errai.marshalling.client.api.MarshallerFactory'
[INFO]       Rebinding org.jboss.errai.marshalling.client.api.MarshallerFactory
[INFO]          Invoking generator org.jboss.errai.marshalling.rebind.MarshallersGenerator
[INFO]             Generating Marshallers Bootstrapper...
[WARNING] [main] INFO org.jboss.errai.common.rebind.CacheUtil - clearing all generation caches...
[WARNING] [Thread-17] INFO org.jboss.errai.reflections.Reflections - Reflections took 434 ms to scan 17 urls, producing 737 keys and 5227 values [using 2 cores]
[WARNING] [main] INFO org.jboss.errai.config.rebind.AsyncGenerators - discovered async generator org.jboss.errai.ui.rebind.TranslationServiceGenerator; for type: org.jboss.errai.ui.client.local.spi.TranslationService
[WARNING] [main] INFO org.jboss.errai.config.rebind.AsyncGenerators - discovered async generator org.jboss.errai.databinding.rebind.BindableProxyLoaderGenerator; for type: org.jboss.errai.databinding.client.BindableProxyLoader
[WARNING] [main] INFO org.jboss.errai.config.rebind.AsyncGenerators - discovered async generator org.jboss.errai.marshalling.rebind.MarshallersGenerator; for type: org.jboss.errai.marshalling.client.api.MarshallerFactory
[WARNING] [main] INFO org.jboss.errai.config.rebind.AsyncGenerators - discovered async generator org.jboss.errai.bus.rebind.RpcProxyLoaderGenerator; for type: org.jboss.errai.bus.client.framework.RpcProxyLoader
[WARNING] [main] INFO org.jboss.errai.config.rebind.AsyncGenerators - discovered async generator org.jboss.errai.ioc.rebind.ioc.bootstrapper.IOCGenerator; for type: org.jboss.errai.ioc.client.Bootstrapper
[WARNING] [main] INFO org.jboss.errai.config.rebind.AsyncGenerators - discovered async generator org.jboss.errai.enterprise.rebind.EventQualifierSerializerGenerator; for type: org.jboss.errai.enterprise.client.cdi.EventQualifierSerializer
[WARNING] [main] ERROR org.jboss.errai.config.rebind.AsyncGenerators - Generator failed to launch
[WARNING] java.lang.NoClassDefFoundError: javax/persistence/spi/PersistenceUnitInfo
[WARNING] 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[WARNING] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[WARNING] 	at java.lang.Class.getConstructor0(Class.java:3075)
[WARNING] 	at java.lang.Class.newInstance(Class.java:412)
[WARNING] 	at org.jboss.errai.config.rebind.AsyncGenerators.startAll(AsyncGenerators.java:151)
[WARNING] 	at org.jboss.errai.config.rebind.AsyncGenerators.getFutureFor(AsyncGenerators.java:55)
[WARNING] 	at org.jboss.errai.config.rebind.AsyncGenerationJob.submit(AsyncGenerationJob.java:109)
[WARNING] 	at org.jboss.errai.config.rebind.AbstractAsyncGenerator.startAsyncGeneratorsAndWaitFor(AbstractAsyncGenerator.java:203)
[WARNING] 	at org.jboss.errai.marshalling.rebind.MarshallersGenerator.generate(MarshallersGenerator.java:75)
[WARNING] 	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
[WARNING] 	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:745)
[WARNING] 	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
[WARNING] 	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
[WARNING] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
[WARNING] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
[WARNING] 	at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
[WARNING] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:519)
[WARNING] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:487)
[WARNING] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.maybeHandleMagicMethodCall(UnifyAst.java:415)
[WARNING] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:402)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:265)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:76)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JBinaryOperation.traverse(JBinaryOperation.java:89)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:94)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:94)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:786)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:778)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[WARNING] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[WARNING] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1401)
[WARNING] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:896)
[WARNING] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
[WARNING] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
[WARNING] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
[WARNING] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
[WARNING] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
[WARNING] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[WARNING] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[WARNING] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[WARNING] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[WARNING] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[WARNING] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[WARNING] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[WARNING] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[WARNING] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[WARNING] Caused by: java.lang.ClassNotFoundException: javax.persistence.spi.PersistenceUnitInfo
[WARNING] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[WARNING] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[WARNING] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[WARNING] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[WARNING] 	... 71 more
```

Later in SuperDevMode the compilation fails and I can't open the application.
